//// Products

export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"



export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"



export const CLEAR_ERROR = "CLEAR_ERROR"



export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS"
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL"


//// Users
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"


export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"



export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"


export const FORGOT_PASSWORD_EMAIL_REQUEST = "FORGOT_PASSWORD_EMAIL_REQUEST"
export const FORGOT_PASSWORD_EMAIL = "FORGOT_PASSWORD_EMAIL"
export const FORGOT_PASSWORD_EMAIL_FAIL = "FORGOT_PASSWORD_EMAIL_FAIL"
export const FORGOT_PASSWORD_EMAIL_RESET = "FORGOT_PASSWORD_EMAIL_RESET"


export const RESET_PASSWORD_EMAIL_REQUEST = "RESET_PASSWORD_EMAIL_REQUEST"
export const RESET_PASSWORD_EMAIL = "RESET_PASSWORD_EMAIL"
export const RESET_PASSWORD_EMAIL_FAIL = "RESET_PASSWORD_EMAIL_FAIL"
export const RESET_PASSWORD_EMAIL_RESET = "RESET_PASSWORD_EMAIL_RESET"


export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER = "LOAD_USER"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"


export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"




export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"


export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO"


export const CREATE_NEW_ORDER_REQUEST = "CREATE_NEW_ORDER_REQUEST"
export const CREATE_NEW_ORDER = "CREATE_NEW_ORDER"
export const CREATE_NEW_ORDER_FAIL = "CREATE_NEW_ORDER_FAIL"